"""ww

Revision ID: 0701d25e883f
Revises: bda61fe1b3b8
Create Date: 2020-08-14 13:34:46.022136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0701d25e883f'
down_revision = 'bda61fe1b3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('id_locker1', sa.Integer(), nullable=True))
    op.add_column('locker_command', sa.Column('id_locker2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locker_command', 'id_locker2')
    op.drop_column('locker_command', 'id_locker1')
    # ### end Alembic commands ###
