"""wwra

Revision ID: 1242e96a4bbb
Revises: fce2b3a5e51b
Create Date: 2020-08-31 17:04:13.971544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1242e96a4bbb'
down_revision = 'fce2b3a5e51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('access', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locker_command', 'access')
    # ### end Alembic commands ###
