"""add row pins

Revision ID: 2579054181e1
Revises: 38d8170adf97
Create Date: 2020-05-07 10:33:25.714971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2579054181e1'
down_revision = '38d8170adf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pins')
    # ### end Alembic commands ###
