"""wwwa

Revision ID: 272f4d2611d5
Revises: cd7022eedbd9
Create Date: 2020-08-12 17:04:22.127933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272f4d2611d5'
down_revision = 'cd7022eedbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sewa_locker', sa.Column('finger_data1', sa.String(length=128), nullable=True))
    op.add_column('sewa_locker', sa.Column('finger_data2', sa.String(length=128), nullable=True))
    op.add_column('sewa_locker', sa.Column('finger_data3', sa.String(length=128), nullable=True))
    op.add_column('sewa_locker', sa.Column('finger_data4', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sewa_locker', 'finger_data4')
    op.drop_column('sewa_locker', 'finger_data3')
    op.drop_column('sewa_locker', 'finger_data2')
    op.drop_column('sewa_locker', 'finger_data1')
    # ### end Alembic commands ###
