"""ww

Revision ID: 449c4d71199f
Revises: 6e2d640a23f6
Create Date: 2020-07-07 19:53:49.196575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449c4d71199f'
down_revision = '6e2d640a23f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('packet2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('packet3', sa.String(), nullable=True))
    op.add_column('users', sa.Column('packet4', sa.String(), nullable=True))
    op.add_column('users', sa.Column('packet5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'packet5')
    op.drop_column('users', 'packet4')
    op.drop_column('users', 'packet3')
    op.drop_column('users', 'packet2')
    # ### end Alembic commands ###
