"""war

Revision ID: 563ed265a75f
Revises: 7ddc50c70ab4
Create Date: 2020-09-04 18:40:47.977559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563ed265a75f'
down_revision = '7ddc50c70ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locker_command', 'enroll_fingerprint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('enroll_fingerprint', sa.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###
