"""aaa

Revision ID: 6e2d640a23f6
Revises: 421a38f2c9ca
Create Date: 2020-06-25 16:44:59.944635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2d640a23f6'
down_revision = '421a38f2c9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sewa_locker', sa.Column('toggle_enroll', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sewa_locker', 'toggle_enroll')
    # ### end Alembic commands ###
