"""war

Revision ID: 7ddc50c70ab4
Revises: a44ef0cc2c22
Create Date: 2020-09-04 18:39:41.697372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddc50c70ab4'
down_revision = 'a44ef0cc2c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locker_command', 'enroll_fingerprint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('enroll_fingerprint', sa.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###
