"""www

Revision ID: 86a7403d361e
Revises: 449c4d71199f
Create Date: 2020-07-07 20:01:08.576251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a7403d361e'
down_revision = '449c4d71199f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sewa_locker', sa.Column('packet2', sa.String(), nullable=True))
    op.add_column('sewa_locker', sa.Column('packet3', sa.String(), nullable=True))
    op.add_column('sewa_locker', sa.Column('packet4', sa.String(), nullable=True))
    op.add_column('sewa_locker', sa.Column('packet5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sewa_locker', 'packet5')
    op.drop_column('sewa_locker', 'packet4')
    op.drop_column('sewa_locker', 'packet3')
    op.drop_column('sewa_locker', 'packet2')
    # ### end Alembic commands ###
