"""war

Revision ID: a44ef0cc2c22
Revises: 582807e8c2c4
Create Date: 2020-09-04 18:38:29.785304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44ef0cc2c22'
down_revision = '582807e8c2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('toggle_lock', sa.Integer(), nullable=True))
    op.drop_column('locker_command', 'enroll_fingerprint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('enroll_fingerprint', sa.VARCHAR(length=8), nullable=True))
    op.drop_column('locker_command', 'toggle_lock')
    # ### end Alembic commands ###
