"""www

Revision ID: b50604feba82
Revises: 1c914f9e0517
Create Date: 2020-08-16 22:54:08.404436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50604feba82'
down_revision = '1c914f9e0517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('access1', sa.String(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('access2', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locker_command', 'access2')
    op.drop_column('locker_command', 'access1')
    # ### end Alembic commands ###
