"""www

Revision ID: cd7022eedbd9
Revises: eee738780acb
Create Date: 2020-08-12 15:54:36.867383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7022eedbd9'
down_revision = 'eee738780acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userfinger1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userfinger2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userfinger3', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userfinger4', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userfinger4')
    op.drop_column('users', 'userfinger3')
    op.drop_column('users', 'userfinger2')
    op.drop_column('users', 'userfinger1')
    # ### end Alembic commands ###
