"""wwaw

Revision ID: fce2b3a5e51b
Revises: cdae57037647
Create Date: 2020-08-31 16:06:17.792831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce2b3a5e51b'
down_revision = 'cdae57037647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_column('locker_command', 'access1')
    op.drop_column('locker_command', 'uid_locker1')
    op.drop_column('locker_command', 'access2')
    op.drop_column('locker_command', 'id_locker1')
    op.drop_column('locker_command', 'enroll_id')
    op.drop_column('locker_command', 'hasil')
    op.drop_column('locker_command', 'uid_locker2')
    op.drop_column('locker_command', 'id_locker2')
    op.drop_column('locker_command', 'statuslocker1')
    op.drop_column('locker_command', 'unlock_locker1')
    op.drop_column('locker_command', 'statuslocker2')
    op.drop_column('locker_command', 'unlock_locker2')
    op.drop_column('locker_command', 'enroll_locker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_command', sa.Column('enroll_locker', sa.VARCHAR(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('unlock_locker2', sa.VARCHAR(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('statuslocker2', sa.VARCHAR(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('unlock_locker1', sa.VARCHAR(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('statuslocker1', sa.VARCHAR(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('id_locker2', sa.INTEGER(), nullable=True))
    op.add_column('locker_command', sa.Column('uid_locker2', sa.INTEGER(), nullable=True))
    op.add_column('locker_command', sa.Column('hasil', sa.VARCHAR(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('enroll_id', sa.INTEGER(), nullable=True))
    op.add_column('locker_command', sa.Column('id_locker1', sa.INTEGER(), nullable=True))
    op.add_column('locker_command', sa.Column('access2', sa.VARCHAR(length=8), nullable=True))
    op.add_column('locker_command', sa.Column('uid_locker1', sa.INTEGER(), nullable=True))
    op.add_column('locker_command', sa.Column('access1', sa.VARCHAR(length=8), nullable=True))
    op.drop_column('locker_command', 'userid')
    # ### end Alembic commands ###
